-- =====================================================================
-- Nova CRM — migration for databases that already have the v1 schema
-- imported. This does NOT drop any existing data. Run once:
--   mysql -u root crm_db < sql/migration_v2.sql
-- =====================================================================

-- 1. Executive permissions + preferred page size on admins
ALTER TABLE `admins`
  ADD COLUMN `permissions` VARCHAR(500) DEFAULT NULL
    COMMENT 'JSON array of modules an executive can access, e.g. ["customers","appointments"]. Ignored for admin/super_admin.'
    AFTER `tenant_id`,
  ADD COLUMN `page_size` INT NOT NULL DEFAULT 10
    COMMENT 'Preferred rows-per-page for list views'
    AFTER `permissions`;

-- Give any existing executives the same three modules they had by default before
UPDATE `admins` SET `permissions` = '["customers","appointments","quotations"]'
  WHERE `role` = 'executive' AND `permissions` IS NULL;

-- 2. Analytics: track enquiries generated per post
ALTER TABLE `analytics`
  ADD COLUMN `post_reference` VARCHAR(255) DEFAULT NULL
    COMMENT 'Which post/content this row is reporting on'
    AFTER `analytics_date`,
  ADD COLUMN `enquiries` INT NOT NULL DEFAULT 0
    COMMENT 'Number of enquiries generated by this post'
    AFTER `post_reference`,
  ADD COLUMN `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    AFTER `created_at`;

-- 3. Settings: make it per-tenant instead of one global row per key
--    (tenant_id = 0 keeps meaning "global/product default", editable by Super Admin;
--    each Admin gets their own override row once they change something in Settings.)
ALTER TABLE `settings`
  DROP PRIMARY KEY,
  ADD COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY FIRST,
  ADD COLUMN `tenant_id` INT NOT NULL DEFAULT 0
    COMMENT '0 = global/product-level default (Super Admin). Otherwise an admin.id.'
    AFTER `id`,
  ADD UNIQUE KEY `settings_tenant_key` (`tenant_id`, `key`);

-- Existing site_name/accent_color/radius rows become the tenant_id=0 (global) row automatically,
-- since the ALTER just adds tenant_id=0 to whatever was already there. Nothing else to do —
-- every Admin will keep seeing this as their color/name until they change it themselves in
-- Settings, at which point a tenant-specific row is created just for them.
